print('This is the Big Five Personality Test')
print('It will help you understand why you act the way that you do and how your personality is structured.')
print('For each statement 1-50 mark how much you agree with on the scale 1-5, where:')
print('		1=disagree')
print('		2=slightly disagree')
print('		3=neutral')
print('		4=slightly agree')
print('		5=agree')

q1 = input('Am the life of the party ')
q2 = input('Feel little concern for others ')
q3 = input('Am always prepared ') 
q4 = input('Get stressed out easily')
q5 = input('Have a rich vocabulary ')
q6 = input('Don\'t talk a lot ')
q7 = input('Am interested in people ')
q8 = input('Leave my belongings around ')
q9 = input('Am relaxed most of the time ')
q10 = input('Have difficulty understanding abstract ideas ')
q11 = input('Feel comfortable around people ')
q12 = input('Insult people ')
q13 = input('Pay attention to details ')
q14 = input('Worry about things ')
q15 = input('Have a vivid imagination ')
q16 = input('Keep in the background ')
q17 = input('Sympathize with others\' feelings ')
q18 = input('Make a mess of things ')
q19 = input('Seldom feel blue ')
q20 = input('Am not interested in abstract ideas ')
q21 = input('Start conversations ')
q22 = input('Am not interested in other people\'s problems ')
q23 = input('Get chores done right away ')
q24 = input('Am easily disturbed ')
q25 = input('Have excellent ideas ')
q26 = input('Have little to say ')
q27	= input('Have a soft heart ')
q28	= input('Often forget to put things back in their proper place ')
q29	= input('Get upset easily ')
q31	= input('Talk to a lot of different people at parties ')
q32	= input('Am not really interested in others ')
q33	= input('Like order ')
q34	= input('Change my mood a lot ')
q35	= input('Am quick to understand things ')
q36	= input('Don\'t like to draw attention to myself ')
q37	= input('Take time out for others ')
q38	= input('Shirk my duties ')
q39	= input('Have frequent mood swings ')
q40	= input('Use difficult words ')
q41	= input('Don\'t mind being the center of attention ')
q42	= input('Feel others\' emotions ')
q43	= input('Follow a schedule ')
q44	= input('Get irritated easily ')
q45	= input('Spend time reflecting on things ')
q46	= input('Am quiet around strangers ')
q47	= input('Make people feel at ease ')
q48	= input('Am exacting in my work ')
q49	= input('Often feel blue ')
q50	= input('Am full of ideas ')

# calculate the final score for O, C, E, A, N
# convert the scores to z-scores
# print the 5 scores and z-scores